package org.jpf.aitest.sample;

import static org.junit.Assert.fail;
import org.junit.Test;
import static org.junit.Assert.assertTrue;
import static org.jpf.aitest.runtime.WriteException.WritePrivateException;

/**
* The class <code>SampleNLPTest</code> contains tests for the class <code>{@link SampleNLP}</code>.
* <p>
* Copyright (c) 2017
* 
* @generatedBy wupf@asiainfo.com at 2018-04-17 07:10:16
* @author Administrator
* @version $Revision: 1.0 $
*/

public class SampleNLPTest  {


  /**
  * Run the add method test.
  *
  * @throws Exception
  * 
  * @generated By wupf@asiainfo.com 
  * @generated at 2018-04-17 07:10:23
  *@see  Modifier=1  String add(String i,String j,int ACCOUNTPAGEQUERYLOGID)
  */
  @Test(timeout=1000)

  public void test_add_R2() throws Exception
  {

    try{

    String i =  "abc123";
    String j =  "abc123";
    int ACCOUNTPAGEQUERYLOGID =  Integer.MAX_VALUE;

  SampleNLP fixture = new SampleNLP();
    String  result=
  fixture.add(i,j,ACCOUNTPAGEQUERYLOGID);

   //请在这里增加检查点:比如 assertEquals(true, result);
    assertTrue(true);

    }catch(Exception ex){
      WritePrivateException(ex,Thread.currentThread().getStackTrace(),true);
      ex.printStackTrace();
      fail();
    }

  }



  /**
  * Run the add method test.
  *
  * @throws Exception
  * 
  * @generated By wupf@asiainfo.com 
  * @generated at 2018-04-17 07:10:23
  *@see  Modifier=1  String add(String i,String j,int ACCOUNTPAGEQUERYLOGID)
  */
  @Test(timeout=1000)

  public void test_add_R3() throws Exception
  {

    try{

    String i =  "abc123";
    String j =  "abc123";
    int ACCOUNTPAGEQUERYLOGID =  Integer.MIN_VALUE;

  SampleNLP fixture = new SampleNLP();
    String  result=
  fixture.add(i,j,ACCOUNTPAGEQUERYLOGID);

   //请在这里增加检查点:比如 assertEquals(true, result);
    assertTrue(true);

    }catch(Exception ex){
      WritePrivateException(ex,Thread.currentThread().getStackTrace(),true);
      ex.printStackTrace();
      fail();
    }

  }



  /**
  * Run the add method test.
  *
  * @throws Exception
  * 
  * @generated By wupf@asiainfo.com 
  * @generated at 2018-04-17 07:10:23
  *@see  Modifier=1  String add(String i,String j,int ACCOUNTPAGEQUERYLOGID)
  */
  @Test(timeout=1000)

  public void test_add_R4() throws Exception
  {

    try{

    String i =  "abc123";
    String j =  "abc123";
    int ACCOUNTPAGEQUERYLOGID =  0;

  SampleNLP fixture = new SampleNLP();
    String  result=
  fixture.add(i,j,ACCOUNTPAGEQUERYLOGID);

   //请在这里增加检查点:比如 assertEquals(true, result);
    assertTrue(true);

    }catch(Exception ex){
      WritePrivateException(ex,Thread.currentThread().getStackTrace(),true);
      ex.printStackTrace();
      fail();
    }

  }



  /**
  * Run the add method test.
  *
  * @throws Exception
  * 
  * @generated By wupf@asiainfo.com 
  * @generated at 2018-04-17 07:10:23
  *@see  Modifier=1  String add(String i,String j,int ACCOUNTPAGEQUERYLOGID)
  */
  @Test(timeout=1000)

  public void test_add_R5() throws Exception
  {

    try{

    String i =  "abc123";
    String j =  "abc123";
    char ACCOUNTPAGEQUERYLOGID =  'a';

  SampleNLP fixture = new SampleNLP();
    String  result=
  fixture.add(i,j,ACCOUNTPAGEQUERYLOGID);

   //请在这里增加检查点:比如 assertEquals(true, result);
    assertTrue(true);

    }catch(Exception ex){
      WritePrivateException(ex,Thread.currentThread().getStackTrace(),true);
      ex.printStackTrace();
      fail();
    }

  }



  /**
  * Run the add method test.
  *
  * @throws Exception
  * 
  * @generated By wupf@asiainfo.com 
  * @generated at 2018-04-17 07:10:23
  *@see  Modifier=1  String add(String i,String j,int ACCOUNTPAGEQUERYLOGID)
  */
  @Test(timeout=1000)

  public void test_add_R6() throws Exception
  {

    try{

    String i =  "abc123";
    String j =  "123";
    int ACCOUNTPAGEQUERYLOGID =  Integer.MAX_VALUE;

  SampleNLP fixture = new SampleNLP();
    String  result=
  fixture.add(i,j,ACCOUNTPAGEQUERYLOGID);

   //请在这里增加检查点:比如 assertEquals(true, result);
    assertTrue(true);

    }catch(Exception ex){
      WritePrivateException(ex,Thread.currentThread().getStackTrace(),true);
      ex.printStackTrace();
      fail();
    }

  }



  /**
  * Run the add method test.
  *
  * @throws Exception
  * 
  * @generated By wupf@asiainfo.com 
  * @generated at 2018-04-17 07:10:24
  *@see  Modifier=1  int add(int ACCOUNTPAGEQUERYLOGID,int PAGEQUERYLOGID)
  */
  @Test(timeout=1000)

  public void test_add_R7() throws Exception
  {

    try{

    int ACCOUNTPAGEQUERYLOGID =  Integer.MAX_VALUE;
    int PAGEQUERYLOGID =  Integer.MAX_VALUE;

  SampleNLP fixture = new SampleNLP();
    int  result=
  fixture.add(ACCOUNTPAGEQUERYLOGID,PAGEQUERYLOGID);

   //请在这里增加检查点:比如 assertEquals(true, result);
    assertTrue(true);

    }catch(Exception ex){
      WritePrivateException(ex,Thread.currentThread().getStackTrace(),true);
      ex.printStackTrace();
      fail();
    }

  }



  /**
  * Run the add method test.
  *
  * @throws Exception
  * 
  * @generated By wupf@asiainfo.com 
  * @generated at 2018-04-17 07:10:24
  *@see  Modifier=1  int add(int ACCOUNTPAGEQUERYLOGID,int PAGEQUERYLOGID)
  */
  @Test(timeout=1000)

  public void test_add_R8() throws Exception
  {

    try{

    int ACCOUNTPAGEQUERYLOGID =  Integer.MAX_VALUE;
    int PAGEQUERYLOGID =  Integer.MIN_VALUE;

  SampleNLP fixture = new SampleNLP();
    int  result=
  fixture.add(ACCOUNTPAGEQUERYLOGID,PAGEQUERYLOGID);

   //请在这里增加检查点:比如 assertEquals(true, result);
    assertTrue(true);

    }catch(Exception ex){
      WritePrivateException(ex,Thread.currentThread().getStackTrace(),true);
      ex.printStackTrace();
      fail();
    }

  }



  /**
  * Run the add method test.
  *
  * @throws Exception
  * 
  * @generated By wupf@asiainfo.com 
  * @generated at 2018-04-17 07:10:24
  *@see  Modifier=1  int add(int ACCOUNTPAGEQUERYLOGID,int PAGEQUERYLOGID)
  */
  @Test(timeout=1000)

  public void test_add_R9() throws Exception
  {

    try{

    int ACCOUNTPAGEQUERYLOGID =  Integer.MAX_VALUE;
    int PAGEQUERYLOGID =  0;

  SampleNLP fixture = new SampleNLP();
    int  result=
  fixture.add(ACCOUNTPAGEQUERYLOGID,PAGEQUERYLOGID);

   //请在这里增加检查点:比如 assertEquals(true, result);
    assertTrue(true);

    }catch(Exception ex){
      WritePrivateException(ex,Thread.currentThread().getStackTrace(),true);
      ex.printStackTrace();
      fail();
    }

  }



  /**
  * Run the add method test.
  *
  * @throws Exception
  * 
  * @generated By wupf@asiainfo.com 
  * @generated at 2018-04-17 07:10:24
  *@see  Modifier=1  int add(int ACCOUNTPAGEQUERYLOGID,int PAGEQUERYLOGID)
  */
  @Test(timeout=1000)

  public void test_add_R10() throws Exception
  {

    try{

    int ACCOUNTPAGEQUERYLOGID =  Integer.MAX_VALUE;
    char PAGEQUERYLOGID =  'a';

  SampleNLP fixture = new SampleNLP();
    int  result=
  fixture.add(ACCOUNTPAGEQUERYLOGID,PAGEQUERYLOGID);

   //请在这里增加检查点:比如 assertEquals(true, result);
    assertTrue(true);

    }catch(Exception ex){
      WritePrivateException(ex,Thread.currentThread().getStackTrace(),true);
      ex.printStackTrace();
      fail();
    }

  }



  /**
  * Run the add method test.
  *
  * @throws Exception
  * 
  * @generated By wupf@asiainfo.com 
  * @generated at 2018-04-17 07:10:24
  *@see  Modifier=1  int add(int ACCOUNTPAGEQUERYLOGID,int PAGEQUERYLOGID)
  */
  @Test(timeout=1000)

  public void test_add_R11() throws Exception
  {

    try{

    int ACCOUNTPAGEQUERYLOGID =  Integer.MIN_VALUE;
    int PAGEQUERYLOGID =  Integer.MAX_VALUE;

  SampleNLP fixture = new SampleNLP();
    int  result=
  fixture.add(ACCOUNTPAGEQUERYLOGID,PAGEQUERYLOGID);

   //请在这里增加检查点:比如 assertEquals(true, result);
    assertTrue(true);

    }catch(Exception ex){
      WritePrivateException(ex,Thread.currentThread().getStackTrace(),true);
      ex.printStackTrace();
      fail();
    }

  }



  /**
  * Run the add method test.
  *
  * @throws Exception
  * 
  * @generated By wupf@asiainfo.com 
  * @generated at 2018-04-17 07:10:24
  *@see  Modifier=1  int add(int ACCOUNTPAGEQUERYLOGID,int PAGEQUERYLOGID)
  */
  @Test(timeout=1000)

  public void test_add_NLP12() throws Exception
  {

    try{

    int ACCOUNTPAGEQUERYLOGID =  464;
    int PAGEQUERYLOGID =  464;

  SampleNLP fixture = new SampleNLP();
    int  result=
  fixture.add(ACCOUNTPAGEQUERYLOGID,PAGEQUERYLOGID);

   //请在这里增加检查点:比如 assertEquals(true, result);
    assertTrue(true);

    }catch(Exception ex){
      WritePrivateException(ex,Thread.currentThread().getStackTrace(),true);
      ex.printStackTrace();
      fail();
    }

  }



}